version: 2

jobs:
  build:
    docker:
      - image: node:current-alpine
    steps:
      - checkout
      - run:
          name: Compute version number
          command: echo "0.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}" | tee version.txt
      - run:
          name: yarn install
          command: yarn install
      - run:
          name: yarn build
          command: |
            cat version.txt
            export __BUILD_VERSION=$(cat version.txt)

            yarn build
      - store_artifacts:
          path: dist/server.js

workflows:
  version: 2

  run:
    jobs:
      - build
