version: 2

jobs:
  prepare-dependencies:
    docker:
      - image: node:current-alpine
    steps:
      - checkout
      - run:
          name: Compute version number
          command: echo "0.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}" | tee version.txt
      - restore_cache:
          keys:
            - yarn-deps-{{ checksum "yarn.lock" }}
            - yarn-deps
      - run:
          name: yarn install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-deps-{{ checksum "yarn.lock" }}-{{ epoch }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    docker:
      - image: node:current-alpine
    steps:
      - attach_workspace:
          at: .
      - run:
          name: yarn build
          command: |
            cat version.txt
            export __BUILD_VERSION=$(cat version.txt)

            yarn build
      - store_artifacts:
          path: dist/server.js
      - persist_to_workspace:
          root: .
          paths:
            - .

  unit-tests:
    docker:
      - image: node:current-alpine
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: |
            yarn test:ci
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results

  deploy-heroku:
    docker:
      - image: archlinux/base:latest
    steps:
      - run:
          name: Install required packages
          command: pacman -Syu --noconfirm tar git
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Heroku
          command: |
            cp dist/server.js heroku
            cd heroku

            # Initialize a separate Git repository
            git init
            git config user.name "Automated by CircleCI"
            git config user.email ""
            git add .
            git commit -a -m Deployment
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/from-cci.git master:master

workflows:
  version: 2

  run:
    jobs:
      - prepare-dependencies
      - build:
          requires:
            - prepare-dependencies
      - unit-tests:
          requires:
            - prepare-dependencies
      - wait-deploy-approval:
          type: approval
          requires:
            - build
            - unit-tests
          filters:
            branches:
              only: main
      - deploy-heroku:
          requires:
            - wait-deploy-approval
          context: heroku
